// Secure Med-Block EHR - Network Configuration
// Deployed on Sepolia Testnet
// Auto-generated by deploy script on 2025-12-06T10:07:13.992Z

// Contract addresses
export const CONTRACT_ADDRESS = "0xf5F6F1aB569Bce5C028bb5a5e63d8e48234d12B1"; // DoctorRegistry
export const HEALTH_RECORD_ADDRESS = "0x4690aECB5a984fa97739CdCc6B3E1a5b2E064fb7"; // HealthRecord
export const POLICY_REGISTRY_ADDRESS = "0xa244cF8a88A8e1F64D7aB6A88c2A4af2EbE5d04A"; // AccessPolicyRegistry

// Sepolia Testnet settings
export const NETWORK = "sepolia";
export const CHAIN_ID = 11155111;
export const RPC_URL = process.env.NEXT_PUBLIC_SEPOLIA_RPC_URL || "https://eth-sepolia.g.alchemy.com/v2/demo";

// Helper functions
export function getContractAddresses() {
  return {
    doctorRegistry: CONTRACT_ADDRESS,
    healthRecord: HEALTH_RECORD_ADDRESS,
    policyRegistry: POLICY_REGISTRY_ADDRESS
  };
}

export function validateContractsDeployed() {
  const missing = [];
  if (!CONTRACT_ADDRESS) missing.push("DoctorRegistry");
  if (!HEALTH_RECORD_ADDRESS) missing.push("HealthRecord");
  if (!POLICY_REGISTRY_ADDRESS) missing.push("PolicyRegistry");

  if (missing.length > 0) {
    return {
      valid: false,
      missing,
      message: `Contracts not deployed: ${missing.join(", ")}. Run: npx hardhat run scripts/deploy-sepolia.js --network sepolia`
    };
  }

  return { valid: true, missing: [], message: "" };
}

export function isCorrectNetwork(connectedChainId) {
  const chainIdNum = typeof connectedChainId === "string"
    ? (connectedChainId.startsWith("0x") ? parseInt(connectedChainId, 16) : parseInt(connectedChainId, 10))
    : connectedChainId;

  return chainIdNum === CHAIN_ID;
}
