const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);
  console.log("Account balance:", (await deployer.getBalance()).toString());

  console.log("\n[1/3] Deploying DoctorRegistry...");
  const DoctorRegistry = await hre.ethers.getContractFactory("DoctorRegistry");
  const doctorRegistry = await DoctorRegistry.deploy();
  await doctorRegistry.deployed();
  console.log("DoctorRegistry:", doctorRegistry.address);

  console.log("\n[2/3] Deploying AccessPolicyRegistry...");
  const AccessPolicyRegistry = await hre.ethers.getContractFactory("AccessPolicyRegistry");
  const policyRegistry = await AccessPolicyRegistry.deploy(doctorRegistry.address);
  await policyRegistry.deployed();
  console.log("AccessPolicyRegistry:", policyRegistry.address);

  console.log("\n[3/3] Deploying HealthRecord...");
  const HealthRecord = await hre.ethers.getContractFactory("HealthRecord");
  const healthRecord = await HealthRecord.deploy(doctorRegistry.address, policyRegistry.address);
  await healthRecord.deployed();
  console.log("HealthRecord:", healthRecord.address);

  const configContent = `// Secure Med-Block EHR - Network Configuration
// Deployed on Sepolia Testnet
// Auto-generated by deploy script on ${new Date().toISOString()}

// Contract addresses
export const CONTRACT_ADDRESS = "${doctorRegistry.address}"; // DoctorRegistry
export const HEALTH_RECORD_ADDRESS = "${healthRecord.address}"; // HealthRecord
export const POLICY_REGISTRY_ADDRESS = "${policyRegistry.address}"; // AccessPolicyRegistry

// Sepolia Testnet settings
export const NETWORK = "sepolia";
export const CHAIN_ID = 11155111;
export const RPC_URL = process.env.NEXT_PUBLIC_SEPOLIA_RPC_URL || "https://eth-sepolia.g.alchemy.com/v2/demo";

// Helper functions
export function getContractAddresses() {
  return {
    doctorRegistry: CONTRACT_ADDRESS,
    healthRecord: HEALTH_RECORD_ADDRESS,
    policyRegistry: POLICY_REGISTRY_ADDRESS
  };
}

export function validateContractsDeployed() {
  const missing = [];
  if (!CONTRACT_ADDRESS) missing.push("DoctorRegistry");
  if (!HEALTH_RECORD_ADDRESS) missing.push("HealthRecord");
  if (!POLICY_REGISTRY_ADDRESS) missing.push("PolicyRegistry");

  if (missing.length > 0) {
    return {
      valid: false,
      missing,
      message: \`Contracts not deployed: \${missing.join(", ")}. Run: npx hardhat run scripts/deploy-sepolia.js --network sepolia\`
    };
  }

  return { valid: true, missing: [], message: "" };
}

export function isCorrectNetwork(connectedChainId) {
  const chainIdNum = typeof connectedChainId === "string"
    ? (connectedChainId.startsWith("0x") ? parseInt(connectedChainId, 16) : parseInt(connectedChainId, 10))
    : connectedChainId;

  return chainIdNum === CHAIN_ID;
}
`;

  fs.writeFileSync(path.join(__dirname, "../config.js"), configContent);
  console.log("\nconfig.js updated");

  const deploymentsDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }

  const deploymentInfo = {
    network: hre.network.name,
    chainId: hre.network.config.chainId,
    deployer: deployer.address,
    timestamp: new Date().toISOString(),
    contracts: {
      DoctorRegistry: doctorRegistry.address,
      AccessPolicyRegistry: policyRegistry.address,
      HealthRecord: healthRecord.address
    }
  };

  fs.writeFileSync(
    path.join(deploymentsDir, `${hre.network.name}.json`),
    JSON.stringify(deploymentInfo, null, 2)
  );

  if (hre.network.name === "sepolia") {
    console.log("\nWaiting for block confirmations...");
    await doctorRegistry.deployTransaction.wait(5);
    await policyRegistry.deployTransaction.wait(5);
    await healthRecord.deployTransaction.wait(5);

    console.log("\nVerifying contracts on Etherscan...");

    try {
      await hre.run("verify:verify", {
        address: doctorRegistry.address,
        constructorArguments: []
      });
    } catch (e) {
      console.log("DoctorRegistry verification:", e.message);
    }

    try {
      await hre.run("verify:verify", {
        address: policyRegistry.address,
        constructorArguments: [doctorRegistry.address]
      });
    } catch (e) {
      console.log("AccessPolicyRegistry verification:", e.message);
    }

    try {
      await hre.run("verify:verify", {
        address: healthRecord.address,
        constructorArguments: [doctorRegistry.address, policyRegistry.address]
      });
    } catch (e) {
      console.log("HealthRecord verification:", e.message);
    }
  }

  console.log("\nDeployment complete!");
  console.log("-------------------");
  console.log("DoctorRegistry:", doctorRegistry.address);
  console.log("AccessPolicyRegistry:", policyRegistry.address);
  console.log("HealthRecord:", healthRecord.address);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
